package com.bromleyoil.smaugdb.model.enums;

public enum ActFlag {
	IS_NPC, SENTINEL, SCAVENGER, NOLOCATE, AGGRESSIVE, STAY_AREA, WIMPY, PET, TRAIN, PRACTICE, IMMORTAL, DEADLY,
	POLYSELF, META_AGGR, GUARDIAN, RUNNING, NOWANDER, MOUNTABLE, MOUNTED, SCHOLAR, SECRETIVE, HARDHAT, MOBINVIS,
	NOASSIST, AUTONOMOUS, PACIFIST, NOATTACK, ANNOYING, STATSHIELD, PROTOTYPE, NOSUMMON, NOSTEAL, INFEST, BLOCKING,
	IS_CLONE, IS_DREAMFORM, IS_SPIRITFORM, IS_PROJECTION, STOP_SCRIPT;
}
