package com.bromleyoil.smaugdb.model.enums;

public enum AffectFlag implements Labelable {
	BLIND, INVISIBLE, DETECT_EVIL, DETECT_INVIS, DETECT_MAGIC, DETECT_HIDDEN, HOLD, SANCTUARY, FAERIE_FIRE, INFRARED,
	CURSE, FLAMING, POISON, PROTECT, PARALYSIS, SNEAK, HIDE, SLEEP, CHARM, FLYING, PASS_DOOR, FLOATING, TRUESIGHT,
	DETECTTRAPS, SCRYING, FIRESHIELD, SHOCKSHIELD, HAUS1, ICESHIELD, POSSESS, BERSERK, AQUA_BREATH, RECURRINGSPELL,
	CONTAGIOUS, ACIDMIST, VENOMSHIELD, ITEM_AURAS, PEOPLE_AURAS, SENSE_DEAD, HEAR_DEAD, SEE_DEAD, FADE, CHAIN_AGONY,
	INFEST, GRAPPLE;
}
