package com.bromleyoil.smaugdb.model.enums;

public enum ApplyType {
	NONE, STR, DEX, INT, WIS, CON, SEX, CLASS, LEVEL, AGE, HEIGHT, WEIGHT, MANA, HIT, MOVE, GOLD, EXP, AC, HITROLL,
	DAMROLL, SAVING_POISON, SAVING_ROD, SAVING_PARA, SAVING_BREATH, SAVING_SPELL, CHA, AFFECT, RESISTANT, IMMUNE,
	SUSCEPTIBLE, WEAPONSPELL, LCK, BACKSTAB, PICK, TRACK, STEAL, SNEAK, HIDE, PALM, DETRAP, DODGE, PEEK, SCAN, GOUGE,
	SEARCH, MOUNT, DISARM, KICK, PARRY, BASH, STUN, PUNCH, CLIMB, GRIP, SCRIBE, BREW, WEARSPELL, REMOVESPELL, EMOTION,
	MENTALSTATE, STRIPSN, REMOVE, DIG, FULL, THIRST, DRUNK, BLOOD, COOK, RECURRINGSPELL, CONTAGIOUS, EXT_AFFECT, ODOR,
	ROOMFLAG, SECTORTYPE, ROOMLIGHT, TELEVNUM, TELEDELAY;
}
