package com.bromleyoil.smaugdb.model.enums;

public enum AttackFlag implements Labelable {
	BITE, CLAWS, TAIL, STING, PUNCH, KICK, TRIP, BASH, STUN, GOUGE, BACKSTAB, FEED, DRAIN, FIREBREATH, FROSTBREATH,
	ACIDBREATH, LIGHTNBREATH, GASBREATH, POISON, NASTYPOISON, GAZE, BLINDNESS, CAUSESERIOUS, EARTHQUAKE, CAUSECRITICAL,
	CURSE, FLAMESTRIKE, HARM, FIREBALL, COLORSPRAY, WEAKEN, SPIRALBLAST, POUNCE;
}
