package com.bromleyoil.smaugdb.model.enums;

public enum ExtraFlag implements Labelable {
	GLOW, HUM, DARK, LOYAL, EVIL, INVIS, MAGIC, NODROP, BLESS, ANTI_GOOD, ANTI_EVIL, ANTI_NEUTRAL, NOREMOVE, INVENTORY,
	ANTI_MAGE, ANTI_THIEF, ANTI_WARRIOR, ANTI_CLERIC, ORGANIC, METAL, DONATION, CLANOBJECT, CLANCORPSE, ANTI_VAMPIRE,
	ANTI_DRUID, HIDDEN, POISONED, COVERING, DEATHROT, BURIED, PROTOTYPE, NOLOCATE, GROUNDROT, LOOTABLE, PERMANENT,
	MULTI_INVOKE, DEATHDROP, SKINNED, NOFILL, BLACKENED, NOSCAVANGE;
}
