package com.bromleyoil.smaugdb.model.enums;

public enum RoomFlag implements Labelable {
	DARK, DEATH, NO_MOB, INDOORS, HOUSE, NEUTRAL, CHAOTIC, NO_MAGIC, NOLOCATE, PRIVATE, SAFE, SOLITARY, PET_SHOP,
	NO_RECALL, DONATION, NODROPALL, SILENCE, LOGSPEECH, NODROP, CLANSTOREROOM, NO_SUMMON, NO_ASTRAL, TELEPORT,
	TELESHOWDESC, NOFLOOR, NOSUPPLICATE, ARENA, NOMISSILE, AUCTION, NOHOVER, PROTOTYPE, DND, TRACK, LIGHT, NOLOG, COLOR,
	NOWHERE, NOYELL, NOQUIT, NOTRACK, NS_CORPSE, NS_RECALL;
}
