package com.bromleyoil.smaugdb.model.enums;

public enum SectorType {
	INSIDE, CITY, FIELD, FOREST, HILLS, MOUNTAIN, WATER_SWIM, WATER_NOSWIM, UNDERWATER, AIR, DESERT, DUNNO, OCEANFLOOR,
	UNDERGROUND, LAVA, SWAMP;
}
