package com.bromleyoil.smaugdb.model.enums;

public enum Special implements Labelable {
	NONE, SPEC_BREATH_ANY, SPEC_BREATH_ACID, SPEC_BREATH_FIRE, SPEC_BREATH_FROST, SPEC_BREATH_GAS, SPEC_BREATH_LIGHTNING,
	SPEC_CAST_ADEPT, SPEC_CAST_CLERIC, SPEC_CAST_JUDGE, SPEC_CAST_MAGE, SPEC_CAST_UNDEAD, SPEC_EXECUTIONER, SPEC_FIDO,
	SPEC_GUARD, SPEC_JANITOR, SPEC_MAYOR, SPEC_POISON, SPEC_THIEF, SPEC_NASTY, SPEC_TROLL_MEMBER, SPEC_OGRE_MEMBER,
	SPEC_PATROLMAN;
}
