package com.bromleyoil.smaugdb.model;

public enum DefenseFlag {
	PARRY, DODGE, HEAL, CURELIGHT, CURESERIOUS, CURECRITICAL, DISPELMAGIC, DISPELEVIL, SANCTUARY, FIRESHIELD,
	SHOCKSHIELD, SHIELD, BLESS, STONESKIN, TELEPORT, MONSUM1, MONSUM2, MONSUM3, MONSUM4, DISARM, ICESHIELD, GRIP,
	TRUESIGHT, ACIDMIST, VENOMSHIELD;
}
