package com.bromleyoil.smaugdb.model;


public enum ItemType {
	NONE, LIGHT, SCROLL, WAND, STAFF, WEAPON, FIREWEAPON, MISSILE, TREASURE, ARMOR, POTION, WORN, FURNITURE, TRASH,
	OLDTRAP, CONTAINER, NOTE, DRINK_CON, KEY, FOOD, MONEY, PEN, BOAT, CORPSE_NPC, CORPSE_PC, FOUNTAIN, PILL, BLOOD,
	BLOODSTAIN, SCRAPS, PIPE, HERB_CON, HERB, INCENSE, FIRE, BOOK, SWITCH, LEVER, PULLCHAIN, BUTTON, DIAL, RUNE,
	RUNEPOUCH, MATCH, TRAP, MAP, PORTAL, PAPER, TINDER, LOCKPICK, SPIKE, DISEASE, OIL, FUEL, PUDDLE, ABACUS,
	MISSILE_WEAPON, PROJECTILE, QUIVER, SHOVEL, SALVE, COOK, KEYRING, ODOR, CHANCE, PIECE, HOUSEKEY, JOURNAL;
}
